name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd ../grocery-api && npm ci
        cd ../grocery-web && npm ci
        cd ../grocery-shared && npm ci
    
    - name: Run tests
      run: |
        npm test
        cd ../grocery-api && npm test
        cd ../grocery-web && npm test
        cd ../grocery-shared && npm test
  
  sca-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install osv-scanner
      run: |
        curl -sSfL https://raw.githubusercontent.com/google/osv-scanner/main/install.sh | sh -s -- -b .
        chmod +x ./osv-scanner
    
    - name: Run vulnerability scan
      run: |
        ./osv-scanner --recursive .
      continue-on-error: true  # Non-blocking as specified in requirements
    
    - name: Verify vulnerabilities
      run: |
        node scripts/verifyVulns.js